<?php

$labels = array();
$labels['imapsync'] = 'Imapsynk';
$labels['imapsyncdelete'] = 'Delete emails after receiving';
$labels['imapsyncenabled'] = 'Aktivera';
$labels['imapsyncfetchall'] = 'Hämta alla E-mail från servern';
$labels['imapsyncfolder'] = 'Fjärrmapp';
$labels['imapsynckeep'] = 'Radera inte mail från fjärrservern';
$labels['imapsyncpollinterval'] = 'Hämtningsintervall';
$labels['imapsyncprotocol'] = 'Protokoll';
$labels['imapsyncserver'] = 'Värdnamn';
$labels['imapsyncusessl'] = 'Använd SSL';
$labels['imapsync_entries'] = 'Accounts to collect for';
$labels['imapsync_to'] = 'Hämta mail till';
$labels['nofetch'] = 'Inga objekt tillgängliga';
$labels['dest_password'] = 'Lokalt lösenord';
$labels['imapsyncskipemptyfolders'] = 'Hoppa över tomma mappar';
$labels['imapsyncsubscribeall'] = 'Prenumerera på alla mappar';
$labels['imapsyncmaxage'] = 'Max ålder på synkade mail';

$messages = array();
$messages['imapsyncabort'] = 'Avbryt';
$messages['imapsyncdelconfirm'] = 'Do you want to delete this entry?';
$messages['imapsynclimitreached'] = 'Gräns uppnådd';
$messages['imapsyncnewentry'] = 'Spara som nytt';
$messages['opnotpermitted'] = 'Behörighet saknas';
$messages['successfullydeleted'] = 'Borttagning slutfördes!';
$messages['successfullydisabled'] = 'Avaktivering lyckades!';
$messages['successfullyenabled'] = 'Aktivering lyckades!';
$messages['successfullysaved'] = 'Sparat!';
$messages['textempty'] = 'Obligatoriska fält är inte ifyllda';

?>
