<?php

$labels = array();
$labels['imapsync'] = 'Imapsync';
$labels['imapsyncdelete'] = 'Delete emails after receiving';
$labels['imapsyncenabled'] = 'Enable';
$labels['imapsyncfetchall'] = 'Fetch all e-mails from server';
$labels['imapsyncfolder'] = 'Remote server folder';
$labels['imapsynckeep'] = 'Do not remove messages from the server';
$labels['imapsyncpollinterval'] = 'Poll interval for the mailbox';
$labels['imapsyncprotocol'] = 'Protocol';
$labels['imapsyncserver'] = 'Server hostname';
$labels['imapsyncusessl'] = 'Use SSL';
$labels['imapsync_entries'] = 'Accounts to collect for';
$labels['imapsync_to'] = 'Collect mail to';
$labels['nofetch'] = 'No entries available';
$labels['dest_password'] = 'local Password';
$labels['imapsyncskipemptyfolders'] = 'skip empty Folders';
$labels['imapsyncsubscribeall'] = 'subscribe all Folders';
$labels['imapsyncmaxage'] = 'max. sync Age (Days)';

$messages = array();
$messages['imapsyncabort'] = 'Avbryt';
$messages['imapsyncdelconfirm'] = 'Do you want to delete this entry?';
$messages['imapsynclimitreached'] = 'Gräns uppnådd';
$messages['imapsyncnewentry'] = 'Spara som nytt';
$messages['opnotpermitted'] = 'Behörighet saknas';
$messages['successfullydeleted'] = 'Borttagning slutfördes!';
$messages['successfullydisabled'] = 'Avaktivering lyckades!';
$messages['successfullyenabled'] = 'Aktivering lyckades!';
$messages['successfullysaved'] = 'Sparat!';
$messages['textempty'] = 'Obligatoriska fält är inte ifyllda';

?>
